test workflow command

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -24,13 +24,14 @@ jobs:
               cdsfile="coding-style-reports.log"
               IFS=":"
               while read -r file_name lines error_type error ; do
+                echo "::workflow-command parameter1=error,parameter2=lines::file_name"
                 echo "$error_type $file_name $lines $error"
               done < "$cdsfile"
-        # - run: |
-        #     if [ -s "coding-style-reports.log" ]
-        #       then
-        #         exit 1
-        #     fi
+        - run: |
+            if [ -s cdsfile ]
+              then
+                exit 1
+            fi
 
   check_program_compilation:
     needs: check_coding_style
